#!/bin/zsh

REALSCALALIB="/home/martin/Applications/scala/scala-2.11.11/lib/scala-library.jar"
RTJAR="/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar"

CLASSES="target/scala-2.11/classes"
ASM="asm/$CLASSES"
SCALAC="scalac/$CLASSES"
SCALACMAIN="scalacmain/$CLASSES"
MAIN="main.Main"

rm -rf classes
mkdir classes

if [ $# -gt 0 ]; then
    MODE="$1"
    shift
else
    MODE="native"
fi

if [ $# -gt 0 ]; then
    SOURCES=(${@})
else
    SOURCES=("tmp/A.scala")
fi

case $MODE in
    "java")
    time \
    java \
        -cp "asm/target/scala-2.11/classes:scalac/target/scala-2.11/classes:scalacmain/target/scala-2.11/classes:$REALSCALALIB" \
        $MAIN \
        -javabootclasspath "$RTJAR:$REALSCALALIB" \
        -bootclasspath "$RTJAR:$REALSCALALIB" \
        -d classes \
        "${SOURCES[@]}"
    ;;

    "native")
    time \
    scalacmain/target/scala-2.11/scalacmain-out \
        -javabootclasspath "$RTJAR:$REALSCALALIB" \
        -bootclasspath "$RTJAR:$REALSCALALIB" \
        -d classes \
        $SOURCES
    ;;
esac
