#!/bin/zsh

REALSCALALIB="/home/martin/Applications/scala/scala-2.11.11/lib/scala-library.jar"
RTJAR="/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar"

CLASSES="target/scala-2.11/classes"
ASM="asm/$CLASSES"
SCALAC="scalac/$CLASSES"
SCALACMAIN="scalacmain/$CLASSES"
MAIN="main.Main"

case $1 in
    "j")
    java \
        -cp "asm/target/scala-2.11/classes:scalac/target/scala-2.11/classes:scalacmain/target/scala-2.11/classes:$REALSCALALIB" \
        $MAIN \
        -javabootclasspath "$RTJAR:$REALSCALALIB" \
        -bootclasspath "$RTJAR:$REALSCALALIB" \
        tmp/A.scala
    ;;

    *)
    scalacmain/target/scala-2.11/scalacmain-out \
        -javabootclasspath "$RTJAR:$REALSCALALIB" \
        -bootclasspath "$RTJAR:$REALSCALALIB" \
        tmp/A.scala \
    ;;
esac
